name: Run 10 times every 10 minutes starting at 8AM

on:
  schedule:
    - cron: '0,10,20,30,40,50 8 * * *'
    - cron: '0,10 9 * * *'

jobs:
  send-post-request:
    runs-on: ubuntu-latest

    steps:
    - name: Send POST request
      run: |
        curl -X POST https://hello-world-lyart-pi.vercel.app/hit
