name: Scheduled POST Request

on:
  schedule:
    # Runs at 08:00 UTC every day. You can adjust the cron schedule as needed.
    - cron: '0 8 * * *'

jobs:
  send-post-request:
    runs-on: ubuntu-latest

    steps:
    - name: Send POST request
      run: |
        curl -X POST https://hello-world-lyart-pi.vercel.app/hit
